# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DLT demo cicd pipeline

concurrency: "1"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DATABRICKS_HOST_NAME: "${{ secrets.DATABRICKS_HOST_NAME }}"
  S3_BUCKET_URI_DEV: ""
  S3_BUCKET_URI_PRD: ""

jobs:
  deploy_test:
    name: "Deploy test DLT pipeline"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: pip install .
    - name: Install Databricks CLI 
      uses: databricks/setup-cli@main
      
    - name: Create DAB file
      working-directory: ./dlt_demo/utils
      run: python create_dab_yaml.py

    - run: databricks bundle deploy
      env:
        DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
        DATABRICKS_BUNDLE_ENV: TEST
        
  run_test:
    name: "Run test DLT pipeline"
    runs-on: ubuntu-latest
    needs:
      - deploy_test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
        
      - name: Install dependencies
        run: pip install .
      - name: Install Databricks CLI 
        uses: databricks/setup-cli@main
        
      - name: Create DAB file
        working-directory: ./dlt_demo/utils
        run: python create_dab_yaml.py
        
      - run: databricks bundle run dlt_demo_pipeline --refresh-all --refresh-mode full
        name: "Run test pipeline"
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: TEST

  
          
    
