# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DLT demo cicd pipeline

concurrency: "1"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  DATABRICKS_HOST_NAME: "${{ secrets.DATABRICKS_HOST_NAME }}"
  S3_BUCKET_URI_DEV: ""
  S3_BUCKET_URI_PRD: ""

jobs:
  deploy_test:
    name: "Deploy test DLT pipeline"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: pip install .
    - name: Install Databricks CLI 
      uses: databricks/setup-cli@main
      
    - name: Create DAB file
      working-directory: ./dlt_demo/utils
      run: python create_dab_yaml.py

    - run: databricks bundle deploy
      env:
        DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
        DATABRICKS_BUNDLE_ENV: TEST
        
  run_test:
    name: "Run test DLT pipeline"
    runs-on: ubuntu-latest
    needs:
      - deploy_test
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - run: |
          pwd
          ls
          if [ -f databricks.yaml ]; then cat databricks.yaml; fi
      - run: databricks bundle run "[TEST] - dlt_demo_pipeline" --refresh-all
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: TEST
  
      

    # Download the Databricks CLI.
    # See https://github.com/databricks/setup-cli
    

    # Deploy the bundle to the "prod" target as defined
    # # in the bundle's settings file.
    # - run: databricks bundle deploy
    #   working-directory: .
    #   env:
    #     DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
    #     DATABRICKS_BUNDLE_ENV: TEST
          
    
